### ISSUE TITLE
Delivery channels: Identify which image sizes we most often served

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/iiif-builder#261]
In order to build useful configuration for the delivery channels work which should determine which sizes (widths) of images are most often served from our source sets in order that we can add configuration to create these in advance.

See https://wellcome.slack.com/archives/CBT40CMKQ/p1704813037082789

**Comment by jcateswellcome** [comment]
Done in conjunction with Digirati to determine new thumbnail policy
